packages:
  - "packages/canvas"
  - "packages/core"
  - "packages/euclid"
  - "packages/gradient"
  - "packages/graphics"
  - "packages/grid"
  - "packages/mock"
  - "packages/player"
  - "packages/reactive"
  - "packages/server"
  - "packages/svg"
  - "packages/texture"
  - "packages/browser"
